apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: shopmicro
type: Opaque
stringData:
  # stringData accepta text pla; Kubernetes ho codificarà a Base64 automàticament
  root-password: "rootpass123"
  user-password: "apppass123"