events {}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # Fitxers estàtics (HTML, CSS, JS)
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Reenviem les crides /api/* a l'api-gateway
        location /api/ {
            proxy_pass http://api-gateway:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}