apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: shopmicro
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: arodriguez5/shopmicro-order-service:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_PRODUCTS_HOST
          valueFrom: { configMapKeyRef: { name: app-config, key: DB_PRODUCTS_HOST } }
        - name: DB_ORDERS_HOST
          valueFrom: { configMapKeyRef: { name: app-config, key: DB_ORDERS_HOST } }
        - name: DB_USER
          valueFrom: { configMapKeyRef: { name: app-config, key: DB_USER } }
        - name: MQ_HOST
          valueFrom: { configMapKeyRef: { name: app-config, key: MQ_HOST } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: db-credentials, key: user-password } }
        - name: MQ_USER
          valueFrom: { secretKeyRef: { name: rabbitmq-credentials, key: username } }
        - name: MQ_PASS
          valueFrom: { secretKeyRef: { name: rabbitmq-credentials, key: password } }
        readinessProbe:
          httpGet: { path: /health, port: 5000 }
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /health, port: 5000 }
          initialDelaySeconds: 30
          periodSeconds: 10