apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: shopmicro
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: arodriguez5/shopmicro-user-service:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom: { configMapKeyRef: { name: app-config, key: DB_ORDERS_HOST } }
        - name: DB_USER
          valueFrom: { configMapKeyRef: { name: app-config, key: DB_USER } }
        - name: DB_NAME
          valueFrom: { configMapKeyRef: { name: app-config, key: DB_ORDERS_NAME } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: db-credentials, key: user-password } }
        - name: JWT_SECRET
          valueFrom: { secretKeyRef: { name: jwt-secret, key: secret } }
        readinessProbe:
          httpGet: { path: /health, port: 5000 }
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /health, port: 5000 }
          initialDelaySeconds: 30
          periodSeconds: 10